config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  root to: "songs#index"
  resources :songs do
    collection do
      get 'search'
    end
    member do
      get 'artist'
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :show]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @song = Song.find(params[:song_id])
    if @song.user_id != current_user.id
       @favorite = Favorite.create(user_id: current_user.id, song_id: @song.id)
    end
  end

  def destroy
    @song = Song.find(params[:song_id])
    @favorite = Favorite.find_by(user_id: current_user.id, song_id: @song.id)
    @favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, song_id: song.id) %>
    <%= link_to song_favorites_path(song.id),method: :post, remote: true do %>
      <i class="fa fa-heart-o" aria-hidden="true"></i>
    <% end %>
    <span class="heart-count1"><%= song.favorites.count %></span>
  <% else %>
    <%= link_to song_favorite_path(song.id, id: song.favorites[0].id),method: :delete, remote: true do %>
      <i class="fa fa-heart" aria-hidden="true"></i>
    <% end %>
    <span class="heart-count2"><%= song.favorites.count %></span>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @song.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { song: @song }) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @song.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { song: @song }) %>");