config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  root to: "songs#index"
  resources :songs do
    collection do
      get 'search'
    end
    member do
      get 'artist'
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2, :twitter]

  has_many :songs
  has_many :favorites
  has_many :sns_credentials

  validates :nickname, :password_confirmation, presence: true

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(nickname: auth.info.name).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    authorization
  end

  def twitter
    authorization
  end
  
  private
  
  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @songs = @user.songs

    favorites = Favorite.where(user_id: @user.id).pluck(:song_id)
    @favorites = Song.find(favorites)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
 <%= render "shared/header" %>
<div class="my_page_all">
    <div class="my_page">
      <span class="name">
          <%=@user.nickname %><span>のマイページ</span>
      </span>
    </div>
    <ul class='song-lists'>
    <% if @songs.length != 0 %>
      <% @songs.each do |song| %> 
      <li class='list'>
        <%= link_to song_path(song.id) do %>
        <div class='song-img-content'>
          <%= image_tag song.image, class: "song-img" %>
        </div>
        <div class='song-info'>
          <h3 class='song-title'>
            <%= song.title %>
          </h3>
           <% end %>
          <div class='song-etc'>
            <span><%= song.artist %><br><%= song.genre %></span>
          </div>
        </div>
      </li>
     <% end %>
     <% else %>
      まだ登録されていません
    <% end %>
    </ul>

    <div class="my_page">
      <span class="name">
          <%=@user.nickname %><span>のお気に入り</span>
      </span>
    </div>
  <ul class='song-lists'>
    <% if @favorites.length != 0 %>
      <% @favorites.each do |song| %>
        <li class='list'>
          <%= link_to song_path(song.id) do %>
          <div class='song-img-content'>
            <%= image_tag song.image, class: "song-img"%>
          </div>
          <div class='song-info'>
            <h3 class='song-titlr'>
              <%= song.title %>
            </h3>
            <% end %>
            <div class='song-etc'>
              <span><%= song.artist %><br><%= song.genre %></span>
            </div>
            <div class='song-user'>
            <span>投稿者:</span><%= link_to User.find(song.user_id).nickname, user_path(song.user_id), class: "user-nickname" %>
            </div>
            <% if user_signed_in? %>
            <div id="favorites_buttons_<%= song.id %>">
              <%= render partial: 'favorites/favorite', locals: { song: song } %>
            </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <% else %>
      お気に入りはまだ登録されていません
    <% end %>
  </ul>
</div>