config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  root to: "songs#index"
  resources :songs do
    collection do
      get 'search'
    end
    member do
      get 'artist'
    end
    resources :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :show]
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :artist
    validates :image
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :song_params_id, except: [:index, :new, :create, :search, :artist]
  before_action :authenticate_user!, except: [:index, :show, :artist]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def index
    @songs = Song.all.page(params[:page]).per(4).order(created_at: :desc)
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    tracks = RSpotify::Track.search(@song.title).first(5)
    @track = tracks.find { |track| track.artists[0].name == @song.artist }
    @track = tracks.first if @track.nil?
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @song.destroy
  end

  def search
    @songs = Song.all
    if params[:search].present?
    @searchartists = RSpotify::Artist.search(params[:search])
    end
  end 

  def artist
    @song = Song.find_by(artist: params[:id])
    @artist = RSpotify::Artist.search(@song.artist)
  end

  private
  def song_params
    params.require(:song).permit(:title, :artist, :genre, :image).merge(user_id: current_user.id)
  end

  def song_params_id
    @song = Song.find(params[:id])
  end

  def move_to_index
    redirect_to root_path if current_user != @song.user
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/artist.html.erb
<%= render "shared/header" %>
<div class="artist-content">
    <div class="text-all">
        <div calss="text-content">
            <h3 class="artist-name"><%= @artist.first.name %> </h3>
            <img src="<%= @artist.first.albums.first.images[0]["url"] %>" width="300" height="300" class="block">
            <img src="<%= @artist.first.albums.second.images[0]["url"] %>" width="300" height="300" class="block">
        </div>
    </div>
    <div class="artist-songs">
        <div class="artist-title">
        <span>プレビュー楽曲</span><h3><%= @artist.first.albums.first.tracks.first.name %> </h3>
        </div>
        <div class="artist-song">
            <iframe class="iframe-song1" src="<%= @artist.first.albums.first.tracks.first.preview_url %>">
        </div>
    </div>
</div>
    

app/views/songs/edit.html.erb
<%# cssは楽曲投稿のものを併用しています。
app/assets/stylesheets/songs/new.css %>

<div class="songs-register-contents">
  <header class="songs-register-header">
    <%= link_to image_tag('music-logo.png' , size: '185x50'), "/" %>
  </header>
  <div class="songs-register-main">
    <h2 class="songs-register-title">商品の情報を入力</h2>
    <%= form_with model: @song ,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# アーティスト画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        アーティスト画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /アーティスト画像 %>
    <%# 楽曲名 %>
    <div class="new-songs">
      <div class="weight-bold-text">
        楽曲名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"songs-text", id:"title", placeholder:"楽曲名" %>
      <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :artist, class:"songs-text", id:"artist", placeholder:"アーティスト名" %>
      <div class="weight-bold-text">
        ジャンル
      </div>
      <%= f.text_area :genre, class:"songs-text", id:"genre", placeholder:"ジャンル名" %>
    </div>
    <%# /楽曲名 %>

    <%# 注意書き %>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', song_path(@song.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="songs-register-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">BMO利用規約</a></li>
      <li><a href="#">著作権に関する表記</a></li>
    </ul>
    <%= link_to image_tag('music-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎BEST MUSIC ONE
    </p>
  </footer>
</div>

app/views/songs/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      What's your Best Music ?
    </h2>
    <p class='service-explain'>
      好きな曲を好きなだけ
    </p>
    <p class='service-explain'>
      共有できます
    </p>
  </div>
  <%# /画面上部の帯部分 %>

  <%# 楽曲一覧 %>
  <div class='song-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿曲
    </div>
    <ul class='song-lists'>

      <% if @songs.present? %>
     <% @songs.each do |song| %> 
      <li class='list'>
        <%= link_to song_path(song.id) do %>
        <div class='song-img-content'>
          <%= image_tag song.image, class: "song-img" %>
        </div>
        <div class='song-info'>
          <h3 class='song-name'>
            <%= song.title %>
          </h3>
           <% end %>
           <%= link_to artist_song_path(song.artist) do %>
          <div class='song-etc'>
            <span><%= song.artist %><br><%= song.genre %></span>
            <% end %>
            <% if user_signed_in? %>
            <div id="favorites_buttons_<%= song.id %>">
              <%= render partial: 'favorites/favorite', locals: { song: song } %>
            </div>
            <% end %>
          </div>
          <div class='song-user'>
            <%= link_to User.find(song.user_id).nickname, user_path(song.user_id), class: "user-nickname" %>
          </div>
        </div>
      </li>
     <% end %>
      <% else %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "song-img" %>
        <div class='song-info'>
          <h3 class='song-name'>
            好きな曲を入れてね！
          </h3>
          <div class='song-etc'>
            <span>アーティスト名<br>ジャンル</span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="nation">
    <%= paginate @songs %>
  </div>
  <%# /楽曲一覧 %>
</div>
<%= link_to(new_song_path, class: 'post-btn') do %>
  <span class='post-btn-text'>投稿する</span>
  <%= image_tag 'icon_music.png' , size: '185x50' ,class: "post-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/songs/new.html.erb
<div class="songs-register-contents">
  <header class="songs-register-header">
    <%= link_to image_tag('music-logo.png' , size: '450x150'), "/" %>
  </header>
  <div class="songs-register-main">
    <h2 class="songs-register-title">楽曲の情報入力</h2>
    <%= form_with model: @song, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# アーティスト画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        アーティスト画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"artist-image" %>
      </div>
    </div>
    <%# /アーティスト画像 %>
    <%# 楽曲名 %>
    <div class="new-songs">
      <div class="weight-bold-text">
        楽曲名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"songs-text", id:"title", placeholder:"楽曲名" %>
      <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :artist, class:"songs-text", id:"artist", placeholder:"アーティスト名" %>
      <div class="weight-bold-text">
        ジャンル
      </div>
      <%= f.text_area :genre, class:"songs-text", id:"genre", placeholder:"ジャンル名" %>
    </div>
    <%# /楽曲名 %>

    <%# 注意書き %>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="songs-register-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">BMO利用規約</a></li>
      <li><a href="#">著作権に関する表記</a></li>
    </ul>
    <%= link_to image_tag('music-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎BEST MUSIC ONE
    </p>
  </footer>
</div>

app/views/songs/search.html.erb
<header class="songs-register-header">
    <%= link_to image_tag('music-logo.png' , size: '185x50'), "/" %>
</header>
  <div class='top-title'>
  <h3>アーティスト名で検索</h3>
  </div>
  <form class="search" >
<%= form_with url: search_songs_path, method: :get, local: true do |form| %>
<div class='input-boxs'>
<%= form.text_field :search %>
</div>
<div class='button'>
<%= form.submit '検索', name: nil %>
</div>
<% end %>
</form>

<div class='search-result'>
<h1>検索結果</h1>
<div>
  <% if @searchartists.present? %>
    <% @searchartists.each do |searchartist| %>
      <div>
        <h3><%= searchartist.name %></h3>
          <% if searchartist.images.any?%>
            <%image = searchartist.images[1]%>
            <%= image_tag(image["url"])%>
          <%else%>
            <%= image_tag("default.jpg")%>
          <%end%>
      </div>
    <% end %>
  <% end %>
</div>

app/views/songs/show.html.erb
<%= render "shared/header" %>

<%# 楽曲の概要 %>
<div class="song-show">
  <div class="song-box">
    <div class="song-img-content">
      <%= image_tag @song.image,class:"song-box-img" %>
    </div>
    <div class="song-info-box">
      <span class="song-title">
        <%= @song.title %>
      </span>
      <%= link_to artist_song_path(@song.artist) do %>
      <span class="song-artist">
        <%= @song.artist%>
      </span>
      <% end %>
      <%= link_to  user_path(@song.user_id), class: "user-nickname" do %>
      <span class='song-user'>
        投稿者:<%= User.find(@song.user_id).nickname %>
      </span>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <% if current_user.id == @song.user.id %>
      <%= link_to "楽曲の編集", edit_song_path(@song.id) , method: :get, class: "song-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", song_path(@song.id), method: :delete, class:"song-destroy" %>
    <% end %>
  <% end %>
    <div class="song-explain-box">
      <span><%= "楽曲プレビュー" %></span>
    </div>
    <img src="<%= @track.album.images.first["url"] %>" width="300" height="300" class="block">
    <div calss="text-all">
    <h3 class="text-light"><%= @track.artists[0].name %> </h3>
    <h3 class="text-light2"><%= @track.artists[0].genres %></h3>
    </div>
    <iframe class="iframe-song" src="<%= @track.preview_url %>">
</div>
  <%# /楽曲の概要 %>

<%= render "shared/second-footer" %>